apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: ai-finance
  labels:
    app: upload-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: upload-service